services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brovider_test
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h 127.0.0.1 -U postgres -d brovider_test']
      interval: 2s
      timeout: 3s
      retries: 15
volumes:
  postgres:
    driver: local
