create table public.keys (
  id character varying not null,
  value text not null,
  provider bigint not null,
  constraint keys_pkey primary key (id)
) TABLESPACE pg_default;

create table public.nodes (
  url text not null,
  network text not null,
  provider bigint not null default '0'::bigint,
  main smallint not null default '0'::smallint,
  constraint nodes_pkey primary key (url)
) TABLESPACE pg_default;

create table public.providers (
  id bigint generated by default as identity not null,
  name text not null,
  constraint providers_pkey primary key (id)
) TABLESPACE pg_default;
