// Create one from https://thegraph.com/studio/apikeys without any restrictions
const NON_RESTRICTED_SUBGRAPH_KEY = process.env.NON_RESTRICTED_SUBGRAPH_KEY;

// Create one from https://thegraph.com/studio/apikeys
const SUBGRAPH_KEY = process.env.SUBGRAPH_KEY;

// Timeout configuration
export const REQUEST_TIMEOUT = 30e3; // 30 seconds

export const RPC_CLIENTS = new Set([
  'api',
  'auction',
  'delegates-api',
  'highlight',
  'mana',
  'mcp',
  'sequencer',
  'sx.js',
  'ui'
]);

export const RPC_NAMESPACES = new Set([
  'account',
  'admin',
  'archive',
  'author',
  'chain',
  'chainHead',
  'chainSpec',
  'childstate',
  'debug',
  'erigon',
  'eth',
  'evm',
  'hardhat',
  'hmy',
  'hmyv2',
  'moon',
  'net',
  'offchain',
  'ots',
  'parity',
  'payment',
  'personal',
  'rpc',
  'starknet',
  'state',
  'subscribe',
  'system',
  'trace',
  'transaction',
  'transactionWatch',
  'txpool',
  'unsubscribe',
  'web3'
]);

export const RPC_METHODS = new Set([
  'chain_getBlockHash',
  'eth_accounts',
  'eth_blobBaseFee',
  'eth_blockNumber',
  'eth_call',
  'eth_chainId',
  'eth_createAccessList',
  'eth_estimateGas',
  'eth_feeHistory',
  'eth_gasPrice',
  'eth_getBalance',
  'eth_getBlockByHash',
  'eth_getBlockByNumber',
  'eth_getBlockReceipts',
  'eth_getBlockTransactionCountByHash',
  'eth_getBlockTransactionCountByNumber',
  'eth_getCode',
  'eth_getFilterChanges',
  'eth_getFilterLogs',
  'eth_getLogs',
  'eth_getProof',
  'eth_getStorageAt',
  'eth_getTransactionByBlockHashAndIndex',
  'eth_getTransactionByBlockNumberAndIndex',
  'eth_getTransactionByHash',
  'eth_getTransactionCount',
  'eth_getTransactionReceipt',
  'eth_maxPriorityFeePerGas',
  'eth_newBlockFilter',
  'eth_newFilter',
  'eth_newPendingTransactionFilter',
  'eth_protocolVersion',
  'eth_sendRawTransaction',
  'eth_simulateV1',
  'eth_syncing',
  'eth_uninstallFilter',
  'hmyv2_getValidatorsStakeByBlockNumber',
  'net_listening',
  'net_peerCount',
  'net_version',
  'starknet_addDeclareTransaction',
  'starknet_addDeployAccountTransaction',
  'starknet_addInvokeTransaction',
  'starknet_blockHashAndNumber',
  'starknet_blockNumber',
  'starknet_call',
  'starknet_chainId',
  'starknet_estimateFee',
  'starknet_estimateMessageFee',
  'starknet_getBlockTransactionCount',
  'starknet_getBlockWithReceipts',
  'starknet_getBlockWithTxHashes',
  'starknet_getBlockWithTxs',
  'starknet_getClass',
  'starknet_getClassAt',
  'starknet_getClassHashAt',
  'starknet_getCompiledCasm',
  'starknet_getEvents',
  'starknet_getMessagesStatus',
  'starknet_getNonce',
  'starknet_getStateUpdate',
  'starknet_getStorageAt',
  'starknet_getStorageProof',
  'starknet_getTransactionByBlockIdAndIndex',
  'starknet_getTransactionByHash',
  'starknet_getTransactionReceipt',
  'starknet_getTransactionStatus',
  'starknet_simulateTransactions',
  'starknet_specVersion',
  'starknet_syncing',
  'starknet_traceBlockTransactions',
  'starknet_traceTransaction',
  'state_getStorage',
  'web3_clientVersion',
  'web3_sha3'
]);

export const subgraphs = {
  subgraph: {
    mainnet: `https://gateway.network.thegraph.com/api/${NON_RESTRICTED_SUBGRAPH_KEY}/subgraphs/id/`,
    arbitrum: `https://gateway-arbitrum.network.thegraph.com/api/${NON_RESTRICTED_SUBGRAPH_KEY}/subgraphs/id/`
  },
  delegation: {
    '1': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/4YgtogVaqoM8CErHWDK8mKQ825BcVdKB8vBYmb4avAQo`,
    '10': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/CAsVTyvLA6vnvDX9zgXifmi3wFM8GYeNHvRpxsABvbYL`,
    '56': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/GuTMtMnx7zukaA1hiHB1uz6FR45gpZX3GtiEN7Cyitjd`,
    '100': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/2XuuZyGrxw72keXKfeHQW7yaGqVa7dyoghkgdGMdC6Az`,
    '137': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/7ynRuH2PPw975dtHkthpZCyQGKBCrxFA8VsYD3KE631B`,
    '146': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/3VUpuJv8J7kdvEMd6ymD1XszpGNQiTjK5oGAnmS3C2Bb`,
    '250': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/szZ3FWewDGHtpeZzf6uQ5dxPY68JNfrGPoWqBXwtBXR`,
    '5000':
      'https://subgraph-api.mantle.xyz/api/public/54a96b6a-f1f4-4124-bf71-17207d243f94/subgraphs/snapshot-labs/snapshot-mantle/v0.0.1/gn',
    '8453': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/9qxDXD1SNnZriMMkCRVAmSdsv4KP6Xvnr8U2CRc5HQWh`,
    '42161': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/HuLBhuKuknXEEUmVmKR8Lsmpi5h1SfNLGcaa1e9tWyMG`,
    '43114': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/5GPQs1wbQXJpt4nJemmEvW3TTf7CPq2MdTvpopTABxhN`,
    '59144': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/5KsUhS8E9xQUu6szt9PUNuUbzJ73C4vi7yQuxFUzmRt4`,
    '81457': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/EtHGr4ekkZkP81yfL2yQEyHqhyBa4nShASoSnjCUgvQd`,
    '84532': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/CdxACSJVLsvfQXRmGYGGM1F93LTkk6VA8anBsxdjJWXn`,
    '11155111': `https://gateway-arbitrum.network.thegraph.com/api/${SUBGRAPH_KEY}/subgraphs/id/2SZVRR6G8txMFtf39aw2aP7BTAawRVwgqHeQXMhr7BRJ`
  }
};
