name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.4.0"

    - name: Set up PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo systemctl start postgresql.service
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'password';"
        sudo -u postgres createdb brovider_test
        sudo -u postgres psql -d brovider_test -f src/helpers/schema.sql

    - name: Setup custom environment variables
      run: |
        echo "NON_RESTRICTED_SUBGRAPH_KEY=${{ secrets.NON_RESTRICTED_SUBGRAPH_KEY }}" >> $GITHUB_ENV
        echo "SUBGRAPH_KEY=${{ secrets.SUBGRAPH_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Test
      run: bun run test
